"use client";
import { useEffect, useMemo, useState } from "react";

type Operator={id:string;name:string;roles:Array<{role:"LEADER"|"ADMIN";target_group_id:string|null}>;pinConfigured:boolean};
type Quiz={id:string;title:string;status:string;selection_mode:"FIXED"|"RANDOM";random_question_count:number|null;published_question_count:number|null;open_at:string|null;close_at:string|null};
type Question={id:string;prompt:string;question_type:"MCQ"|"OX";selected:boolean;difficulty:string|null};
type Person={id:string;display_name:string;active:boolean;ranking_eligible:boolean;group_id?:string|null;group_name?:string|null};
type Group={id:string;name:string;active:boolean};
type ImportItem={id:string;source_name:string;month_key:string|null;created_at:string;summary:any};
type ImportPreview={fileName:string;hash:string;totalQuestions:number;totalErrors:number;replacementDiff?:{oldCount:number;newCount:number;added:string[];removed:string[]}|null;weeks:Array<{sheetName:string;title:string;lifeDateRange:string;bibleRange:string;openAt:string;closeAt:string;memo:string;questions:any[];errors:string[]}>};

async function jsonFetch(url:string,init?:RequestInit){const r=await fetch(url,init);const j=await r.json();if(!r.ok)throw new Error(j.error??"요청에 실패했습니다.");return j;}

export default function OperatorPage(){
 const [operators,setOperators]=useState<Operator[]>([]); const [session,setSession]=useState<any>(null); const [selectedOperator,setSelectedOperator]=useState(""); const [pin,setPin]=useState(""); const [setupCode,setSetupCode]=useState(""); const [newPin,setNewPin]=useState(""); const [error,setError]=useState(""); const [success,setSuccess]=useState("");
 const [tab,setTab]=useState<"dashboard"|"quiz"|"import"|"people"|"permissions"|"season"|"monthly"|"special"|"stats">("dashboard"); const [leaderDashboard,setLeaderDashboard]=useState<any>(null); const [adminStats,setAdminStats]=useState<any>(null); const [dashboard,setDashboard]=useState<any>(null); const [quizzes,setQuizzes]=useState<Quiz[]>([]); const [activeQuiz,setActiveQuiz]=useState(""); const [questions,setQuestions]=useState<Question[]>([]); const [selectionMode,setSelectionMode]=useState<"FIXED"|"RANDOM">("FIXED"); const [randomCount,setRandomCount]=useState(10); const [publishStart,setPublishStart]=useState(""); const [publishEnd,setPublishEnd]=useState(""); const [people,setPeople]=useState<Person[]>([]); const [groups,setGroups]=useState<Group[]>([]); const [busy,setBusy]=useState(false);
 const [selectedPeople,setSelectedPeople]=useState<string[]>([]); const [moveGroup,setMoveGroup]=useState(""); const [moveDate,setMoveDate]=useState(()=>new Date().toISOString().slice(0,10));
 const [currentPinChange,setCurrentPinChange]=useState(""); const [newPinChange,setNewPinChange]=useState("");
 const [rolePerson,setRolePerson]=useState(""); const [role,setRole]=useState<"LEADER"|"ADMIN">("LEADER"); const [roleGroup,setRoleGroup]=useState(""); const [roleDate,setRoleDate]=useState(()=>new Date().toISOString().slice(0,10));
 const [imports,setImports]=useState<ImportItem[]>([]); const [importMode,setImportMode]=useState<"NEW"|"REPLACE">("NEW"); const [monthKey,setMonthKey]=useState(""); const [preview,setPreview]=useState<ImportPreview|null>(null); const [replaceImportId,setReplaceImportId]=useState(""); const [importUrl,setImportUrl]=useState("");

 const [seasons,setSeasons]=useState<any[]>([]); const [periods,setPeriods]=useState<any[]>([]); const [specials,setSpecials]=useState<any[]>([]);
 const [seasonName,setSeasonName]=useState(""); const [seasonStart,setSeasonStart]=useState(""); const [seasonEnd,setSeasonEnd]=useState("");
 const [periodName,setPeriodName]=useState(""); const [periodSeason,setPeriodSeason]=useState(""); const [periodStart,setPeriodStart]=useState(""); const [periodEnd,setPeriodEnd]=useState("");
 const [specialTitle,setSpecialTitle]=useState(""); const [specialMode,setSpecialMode]=useState("PASS"); const [passScore,setPassScore]=useState(80); const [retryMode,setRetryMode]=useState("UNTIL_PASS"); const [maxAttempts,setMaxAttempts]=useState(3); const [answerRevealMode,setAnswerRevealMode]=useState("AFTER_PASS"); const [answerRevealAt,setAnswerRevealAt]=useState(""); const [specialMessage,setSpecialMessage]=useState(""); const [issuePass,setIssuePass]=useState(true);
 const currentOperator=operators.find(o=>o.id===selectedOperator); const selectedCount=useMemo(()=>questions.filter(q=>q.selected).length,[questions]);
 function localDateTimeValue(iso:string|null){if(!iso)return "";const d=new Date(iso);const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16);}
 function defaultWeeklyWindow(){const now=new Date();const day=now.getDay();const diff=(day+6)%7;const start=new Date(now);start.setDate(now.getDate()-diff);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(start.getDate()+5);end.setHours(23,59,0,0);const fmt=(d:Date)=>{const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16);};return [fmt(start),fmt(end)] as const;}
 function showSuccess(message:string){setError("");setSuccess(message);window.setTimeout(()=>setSuccess(current=>current===message?"":current),4500);}
 async function bootstrap(){try{const [list,me]=await Promise.all([jsonFetch("/api/operator/list"),jsonFetch("/api/operator/me")]);setOperators(list.operators);setSession(me.session);if(list.operators[0])setSelectedOperator(v=>v||list.operators[0].id);if(me.session){if(me.session.roles?.some((r:any)=>r.role==="ADMIN"))await loadAdmin();else await loadLeader();}}catch(e){setError(e instanceof Error?e.message:"불러오기 실패");}}
 async function loadLeader(){const d=await jsonFetch("/api/leader/dashboard");setLeaderDashboard(d);} async function loadAdmin(){const [d,q,p,g,im,st]=await Promise.all([jsonFetch("/api/admin/dashboard"),jsonFetch("/api/admin/quizzes"),jsonFetch("/api/admin/people"),jsonFetch("/api/admin/groups"),jsonFetch("/api/admin/import/list"),jsonFetch("/api/admin/stats")]);setAdminStats(st);setDashboard(d);setQuizzes(q.quizzes??[]);setPeople(p.people??[]);setGroups(g.groups??[]);setImports(im.imports??[]);if((q.quizzes??[])[0])setActiveQuiz(v=>v||(q.quizzes??[])[0].id);if((p.people??[])[0])setRolePerson(v=>v||(p.people??[])[0].id);if((g.groups??[])[0]){setMoveGroup(v=>v||(g.groups??[])[0].id);setRoleGroup(v=>v||(g.groups??[])[0].id);}}
 async function loadQuestions(id:string){if(!id)return;const j=await jsonFetch(`/api/admin/questions?quizId=${id}`);setQuestions(j.questions??[]);const q=quizzes.find(x=>x.id===id);if(q){setSelectionMode(q.selection_mode);setRandomCount(q.random_question_count??10);if(q.open_at&&q.close_at){setPublishStart(localDateTimeValue(q.open_at));setPublishEnd(localDateTimeValue(q.close_at));}else{const [start,end]=defaultWeeklyWindow();setPublishStart(start);setPublishEnd(end);}}}
 useEffect(()=>{void bootstrap();},[]);useEffect(()=>{if(session&&activeQuiz)void loadQuestions(activeQuiz);},[session,activeQuiz]);
 async function login(){setBusy(true);setError("");try{const j=await jsonFetch("/api/operator/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({personId:selectedOperator,pin})});setSession({roles:j.roles});setPin("");if(j.roles?.some((r:any)=>r.role==="ADMIN"))await loadAdmin();else await loadLeader();}catch(e){setError(e instanceof Error?e.message:"로그인 실패");}finally{setBusy(false);}}
 async function setup(){setBusy(true);setError("");try{const j=await jsonFetch("/api/operator/setup-pin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({personId:selectedOperator,setupCode,pin:newPin})});setSession({roles:j.roles});setSetupCode("");setNewPin("");if(j.roles?.some((r:any)=>r.role==="ADMIN"))await loadAdmin();else await loadLeader();}catch(e){setError(e instanceof Error?e.message:"PIN 설정 실패");}finally{setBusy(false);}}
 async function logout(){await jsonFetch("/api/operator/logout",{method:"POST"});setSession(null);setDashboard(null);}
 async function saveSelection(){setBusy(true);setError("");setSuccess("");try{await jsonFetch("/api/admin/questions/select",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({quizId:activeQuiz,selectedQuestionIds:questions.filter(q=>q.selected).map(q=>q.id),selectionMode,randomQuestionCount:randomCount})});await loadAdmin();await loadQuestions(activeQuiz);showSuccess(`문제 선택이 저장되었습니다. ${selectedCount}개 문제를 출제 대상으로 저장했습니다.`);}catch(e){setError(e instanceof Error?e.message:"저장 실패");}finally{setBusy(false);}}
 async function publishQuiz(){if(!activeQuiz||!publishStart||!publishEnd)return;setBusy(true);setError("");setSuccess("");try{const j=await jsonFetch("/api/admin/quizzes/publish",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({quizId:activeQuiz,openAt:new Date(publishStart).toISOString(),closeAt:new Date(publishEnd).toISOString()})});await loadAdmin();showSuccess(j.status==="OPEN"?"퀴즈가 공개되었습니다. 참가자 화면에서 지금 바로 시작할 수 있습니다.":"퀴즈가 예약되었습니다. 설정한 공개 시작 시간부터 참가자 화면에 표시됩니다.");}catch(e){setError(e instanceof Error?e.message:"퀴즈 공개 실패");}finally{setBusy(false);}}

 async function changeQuizStatus(action:"CLOSE"|"DRAFT"){if(!activeQuiz)return;if(action==="DRAFT"&&!confirm("공개를 취소하고 DRAFT로 되돌릴까요? 공개 기간도 초기화됩니다."))return;setBusy(true);try{const j=await jsonFetch("/api/admin/quizzes/status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({quizId:activeQuiz,action})});await loadAdmin();await loadQuestions(activeQuiz);showSuccess(j.status==="CLOSED"?"퀴즈를 마감했습니다. 신규 공식 응시는 시작할 수 없습니다.":"퀴즈 공개를 취소하고 DRAFT로 되돌렸습니다.");}catch(e){setError(e instanceof Error?e.message:"상태 변경 실패");}finally{setBusy(false);}}
 async function resetTestRecords(){if(!activeQuiz||!confirm("이 퀴즈의 TEST 기록만 모두 초기화할까요? 공식/연습 기록은 삭제되지 않습니다."))return;setBusy(true);try{const j=await jsonFetch("/api/admin/test-reset",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({quizId:activeQuiz})});showSuccess(`TEST 기록을 초기화했습니다. ${j.deletedSessions??0}개 세션 삭제`);}catch(e){setError(e instanceof Error?e.message:"TEST 기록 초기화 실패");}finally{setBusy(false);}}
 async function togglePerson(p:Person){setBusy(true);try{await jsonFetch("/api/admin/people",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:p.id,name:p.display_name,active:!p.active,rankingEligible:p.ranking_eligible})});await loadAdmin();showSuccess(`${p.display_name}님을 ${p.active?"비활성":"활성"} 상태로 변경했습니다.`);}catch(e){setError(e instanceof Error?e.message:"참가자 수정 실패");}finally{setBusy(false);}}
 async function toggleGroup(g:Group){setBusy(true);try{await jsonFetch("/api/admin/groups",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:g.id,name:g.name,active:!g.active})});await loadAdmin();showSuccess(`${g.name} 셀을 ${g.active?"비활성":"활성"} 상태로 변경했습니다.`);}catch(e){setError(e instanceof Error?e.message:"셀 수정 실패");}finally{setBusy(false);}}
 async function addPerson(){const name=prompt("새 참가자 이름");if(!name)return;setBusy(true);try{await jsonFetch("/api/admin/people",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})});await loadAdmin();showSuccess(`${name} 참가자가 등록되었습니다.`);}catch(e){setError(e instanceof Error?e.message:"참가자 추가 실패");}finally{setBusy(false);}}
 async function addGroup(){const name=prompt("새 셀 이름");if(!name)return;setBusy(true);try{await jsonFetch("/api/admin/groups",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})});await loadAdmin();showSuccess(`${name} 셀이 등록되었습니다.`);}catch(e){setError(e instanceof Error?e.message:"셀 추가 실패");}finally{setBusy(false);}}
 async function movePeople(){if(!selectedPeople.length)return;setBusy(true);try{await jsonFetch("/api/admin/memberships/bulk-move",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({personIds:selectedPeople,groupId:moveGroup,effectiveDate:moveDate})});setSelectedPeople([]);await loadAdmin();showSuccess("선택한 참가자의 셀 이동을 저장했습니다.");}catch(e){setError(e instanceof Error?e.message:"이동 실패");}finally{setBusy(false);}}
 async function changePin(){setBusy(true);try{await jsonFetch("/api/operator/change-pin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPin:currentPinChange,newPin:newPinChange})});setCurrentPinChange("");setNewPinChange("");showSuccess("PIN을 변경했습니다.");}catch(e){setError(e instanceof Error?e.message:"PIN 변경 실패");}finally{setBusy(false);}}
 async function grantRole(){setBusy(true);try{const j=await jsonFetch("/api/admin/roles/grant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({personId:rolePerson,role,targetGroupId:role==="LEADER"?roleGroup:null,effectiveDate:roleDate})});alert(j.pinAlreadyConfigured?"권한을 부여했습니다. 기존 4자리 PIN을 그대로 사용합니다.":`권한을 부여했습니다.\n1회용 설정코드: ${j.setupCode}\n24시간 안에 사용하세요.`);}catch(e){setError(e instanceof Error?e.message:"권한 부여 실패");}finally{setBusy(false);}}
 async function revokeRole(personId:string,roleName:"LEADER"|"ADMIN"){if(!confirm(`${roleName} 권한을 해제할까요?`))return;setBusy(true);try{await jsonFetch("/api/admin/roles/revoke",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({personId,role:roleName,effectiveDate:new Date().toISOString().slice(0,10)})});await bootstrap();showSuccess("권한을 해제했습니다.");}catch(e){setError(e instanceof Error?e.message:"권한 해제 실패");}finally{setBusy(false);}}
 async function previewFile(file:File){setBusy(true);setError("");setSuccess("");try{const f=new FormData();f.append("file",file);f.append("mode",importMode);f.append("replaceImportId",replaceImportId);const r=await fetch("/api/admin/import/preview",{method:"POST",body:f});const j=await r.json();if(!r.ok)throw new Error(j.error??"미리보기 실패");setPreview(j);showSuccess(`Excel 파일을 읽었습니다. ${j.totalQuestions}개 후보 문제를 확인해주세요.`);}catch(e){setError(e instanceof Error?e.message:"미리보기 실패");}finally{setBusy(false);}}
 async function previewUrl(){if(!importUrl.trim())return;setBusy(true);setError("");setSuccess("");try{const j=await jsonFetch("/api/admin/import/preview-url",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:importUrl.trim(),mode:importMode,replaceImportId})});setPreview(j);showSuccess(`주소에서 Excel 파일을 읽었습니다. ${j.totalQuestions}개 후보 문제를 확인해주세요.`);}catch(e){setError(e instanceof Error?e.message:"주소 불러오기 실패");}finally{setBusy(false);}}
 async function commitImport(){if(!preview)return;setBusy(true);setError("");setSuccess("");try{const j=await jsonFetch("/api/admin/import/commit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fileName:preview.fileName,sourceHash:preview.hash,monthKey,mode:importMode,replaceImportId:replaceImportId||null,weeks:preview.weeks})});setPreview(null);await loadAdmin();setTab("quiz");showSuccess(`퀴즈 후보가 등록되었습니다. ${j.createdQuizIds?.length??0}개 주차 퀴즈를 만들었습니다. 문제를 선택한 뒤 공개해주세요.`);}catch(e){setError(e instanceof Error?e.message:"Import 실패");}finally{setBusy(false);}}

 async function loadSeasonSpecial(){const [s,p,sp]=await Promise.all([jsonFetch("/api/admin/seasons"),jsonFetch("/api/admin/monthly-periods"),jsonFetch("/api/admin/special")]);setSeasons(s.seasons??[]);setPeriods(p.periods??[]);setSpecials(sp.specials??[]);if((s.seasons??[])[0])setPeriodSeason(v=>v||(s.seasons??[])[0].id);}
 async function createSeasonUi(){await jsonFetch("/api/admin/seasons",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:seasonName,startsOn:seasonStart,endsOn:seasonEnd,active:true})});setSeasonName("");await loadSeasonSpecial();showSuccess("Season이 생성되고 활성화되었습니다.");}
 async function createPeriodUi(){await jsonFetch("/api/admin/monthly-periods",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({seasonId:periodSeason,name:periodName,startsOn:periodStart,endsOn:periodEnd})});setPeriodName("");await loadSeasonSpecial();await loadAdmin();showSuccess("월간 기간이 생성되고 해당 기간의 Weekly Quiz가 자동 연결되었습니다.");}
 async function settlePeriodUi(id:string){if(!confirm("이 월간 결과를 확정할까요? 확정 후 Winner 기록이 생성됩니다."))return;const j=await jsonFetch("/api/admin/monthly-settle",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({periodId:id})});showSuccess(`월간 결산이 확정되었습니다. Winner ${j.winners?.length??0}명`);await loadSeasonSpecial();}
 async function createSpecialUi(){await jsonFetch("/api/admin/special",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:specialTitle,specialMode,passScore,retryMode,maxAttempts,answerRevealMode,answerRevealAt:answerRevealMode==="AT_TIME"&&answerRevealAt?new Date(answerRevealAt).toISOString():null,customPassMessage:specialMessage||null,issuePass,publishedQuestionCount:10,selectionMode:"FIXED"})});setSpecialTitle("");await loadSeasonSpecial();await loadAdmin();showSuccess("Special Quiz 초안이 생성되었습니다. 퀴즈 · 문제에서 문제를 선택하고 공개해주세요.");}
 useEffect(()=>{if(session && ["season","monthly","special"].includes(tab))void loadSeasonSpecial();},[session,tab]);
 if(session&&!session.roles?.some((r:any)=>r.role==="ADMIN"))return <main className="adminShell"><aside className="adminNav"><div><p className="eyebrow">주간 셀 퀴즈</p><h2>우리 셀 관리</h2></div><nav><button className="active">참여현황</button></nav><div><button className="ghost" onClick={()=>void logout()}>운영자 모드 나가기</button></div></aside><section className="adminMain"><div className="adminTitleRow"><div><p className="eyebrow">LEADER VIEW</p><h1>{leaderDashboard?.currentQuiz?.title??"이번 주 퀴즈"}</h1></div><span className="statusPill">LEADER</span></div><div className="adminStats"><article><span>이번 주 참여</span><strong>{leaderDashboard?.submitted??0} / {leaderDashboard?.eligible??0}</strong></article><article><span>셀 평균</span><strong>{leaderDashboard?.average??"–"}점</strong></article><article><span>이번 달 현재 1위</span><strong>{leaderDashboard?.monthlyLeader?.name??"–"}</strong></article></div><section className="adminPanel"><h3>우리 셀 참여현황</h3>{(leaderDashboard?.members??[]).map((m:any)=><div className="adminRow" key={m.personId}><span><strong>{m.name}</strong><small>{m.submitted?`이번 주 ${m.weeklyScore}점 · 이번 달 ${m.monthlyScore}점`:"이번 주 미참여"}</small></span><span className={m.submitted?"statusPill":"statusPill warn"}>{m.submitted?"완료":"미참여"}</span></div>)}</section></section></main>;
 if(!session)return <main className="operatorShell"><section className="operatorLogin"><p className="eyebrow">OPERATOR MODE</p><h1>운영자 로그인</h1><label>운영자<select value={selectedOperator} onChange={e=>setSelectedOperator(e.target.value)}>{operators.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>{currentOperator?.pinConfigured?<><label>4자리 PIN<input inputMode="numeric" maxLength={4} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,4))}/></label><button className="primary" disabled={busy||pin.length!==4} onClick={()=>void login()}>로그인</button></>:<><p className="helper">처음 운영자 권한을 받았다면 Admin에게 받은 6자리 설정코드로 본인의 4자리 PIN을 만드세요.</p><label>설정코드<input inputMode="numeric" value={setupCode} onChange={e=>setSetupCode(e.target.value.replace(/\D/g,"").slice(0,6))}/></label><label>새 4자리 PIN<input inputMode="numeric" maxLength={4} value={newPin} onChange={e=>setNewPin(e.target.value.replace(/\D/g,"").slice(0,4))}/></label><button className="primary" disabled={busy||newPin.length!==4||setupCode.length!==6} onClick={()=>void setup()}>PIN 만들고 시작</button></>}{error&&<p className="operatorError">{error}</p>}<a className="textLink" href="/">참가자 화면으로</a></section></main>;
 return <main className="adminShell"><aside className="adminNav"><div><p className="eyebrow">주간 셀 퀴즈</p><h2>운영자</h2></div><nav>{[["dashboard","대시보드"],["quiz","퀴즈 · 문제"],["import","Excel"],["people","참가자 · 셀"],["season","Season"],["monthly","월간 결산"],["special","Special"],["stats","통계"],["permissions","권한"]].map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k as any)}>{l}</button>)}</nav><div><button className="ghost" onClick={()=>void logout()}>운영자 모드 나가기</button></div></aside><section className="adminMain">{success&&<div className="successBanner">✓ {success}</div>}{error&&<div className="errorBanner">{error}</div>}
 {tab==="dashboard"&&<><p className="eyebrow">ADMIN DASHBOARD</p><h1>이번 주 운영 현황</h1><div className="adminStats"><article><span>참여</span><strong>{dashboard?.participation?.submitted??0} / {dashboard?.participation?.eligible??0}</strong></article><article><span>활성 참가자</span><strong>{dashboard?.activePeople??0}</strong></article><article><span>활성 셀</span><strong>{dashboard?.activeGroups??0}</strong></article></div><section className="adminPanel"><h3>현재 퀴즈</h3><p className="bigText">{dashboard?.currentQuiz?.title??"등록된 퀴즈 없음"}</p><span className="statusPill">{dashboard?.currentQuiz?.status??"EMPTY"}</span></section></>}
 {tab==="quiz"&&<><div className="adminTitleRow"><div><p className="eyebrow">QUESTION CANDIDATES</p><h1>문제 선택 · 공개</h1></div><div className="selectionCount"><strong>{selectedCount}</strong>개 선택 / 후보 {questions.length}개</div></div><div className="adminControls"><select value={activeQuiz} onChange={e=>setActiveQuiz(e.target.value)}>{quizzes.map(q=><option key={q.id} value={q.id}>{q.title} · {q.status}</option>)}</select><label><input type="radio" checked={selectionMode==="FIXED"} onChange={()=>setSelectionMode("FIXED")}/> 고정 출제</label><label><input type="radio" checked={selectionMode==="RANDOM"} onChange={()=>setSelectionMode("RANDOM")}/> 랜덤 출제</label>{selectionMode==="RANDOM"&&<label>출제 수 <input className="smallInput" type="number" min={1} max={selectedCount||1} value={randomCount} onChange={e=>setRandomCount(Number(e.target.value))}/></label>}<button className="primary" disabled={busy||selectedCount===0} onClick={()=>void saveSelection()}>선택 저장</button></div><section className="adminPanel publishPanel"><div className="adminTitleRow"><div><h3>퀴즈 공개</h3><p>선택 저장 후 공개 기간을 확인하고 공개하세요.</p></div><span className="statusPill">{quizzes.find(q=>q.id===activeQuiz)?.status??"DRAFT"}</span></div><div className="formGrid"><label>공개 시작<input type="datetime-local" value={publishStart} onChange={e=>setPublishStart(e.target.value)}/></label><label>마감<input type="datetime-local" value={publishEnd} onChange={e=>setPublishEnd(e.target.value)}/></label></div><div className="adminControls"><button className="primary" disabled={busy||selectedCount===0||!publishStart||!publishEnd} onClick={()=>void publishQuiz()}>퀴즈 공개 / 예약</button><button className="ghost" disabled={busy||!activeQuiz||selectedCount===0} onClick={()=>window.open(`/?test=1&quizId=${encodeURIComponent(activeQuiz)}`,"_blank","noopener,noreferrer")}>TEST 모드로 열기</button><button className="ghost" disabled={busy||!activeQuiz} onClick={()=>void resetTestRecords()}>TEST 기록 초기화</button><button className="ghost" disabled={busy||!activeQuiz} onClick={()=>void changeQuizStatus("CLOSE")}>지금 마감</button><button className="ghost" disabled={busy||!activeQuiz} onClick={()=>void changeQuizStatus("DRAFT")}>공개 취소 → DRAFT</button></div></section><div className="candidateList">{questions.map((q,i)=><label key={q.id} className={q.selected?"candidate selected":"candidate"}><input type="checkbox" checked={q.selected} onChange={e=>setQuestions(prev=>prev.map(x=>x.id===q.id?{...x,selected:e.target.checked}:x))}/><span className="candidateNo">{i+1}</span><span><strong>{q.prompt}</strong><small>{q.question_type} · {q.difficulty??"MEDIUM"}</small></span></label>)}</div></>}
 {tab==="import"&&<><p className="eyebrow">MONTHLY CONTENT</p><h1>Excel 문제 불러오기</h1><div className="adminPanel importPanel"><div className="adminControls"><label><input type="radio" checked={importMode==="NEW"} onChange={()=>setImportMode("NEW")}/> 새 월 파일 불러오기</label><label><input type="radio" checked={importMode==="REPLACE"} onChange={()=>setImportMode("REPLACE")}/> 기존 월 파일 교체</label></div><p><a href="/templates/주간셀퀴즈_문제템플릿_원본.xlsx">원본 Excel 템플릿 다운로드</a> 후 복사본에 문제를 작성하세요.</p><div className="formGrid"><label>월 키<input placeholder="2026-11" value={monthKey} onChange={e=>setMonthKey(e.target.value)}/></label>{importMode==="REPLACE"&&<label>교체 대상 월 파일<select value={replaceImportId} onChange={e=>setReplaceImportId(e.target.value)}><option value="">선택</option>{imports.map(x=><option key={x.id} value={x.id}>{x.month_key??"월 미지정"} · {x.source_name}</option>)}</select></label>}<label>Excel 파일<input type="file" accept=".xlsx" onChange={e=>{const f=e.target.files?.[0];if(f)void previewFile(f);}}/></label><label>또는 HTTPS 파일 주소<input value={importUrl} onChange={e=>setImportUrl(e.target.value)} placeholder="https://.../quiz.xlsx"/><button type="button" className="ghost" disabled={busy||!importUrl.trim()} onClick={()=>void previewUrl()}>주소에서 불러오기</button></label></div></div>{preview&&<section className="adminPanel"><div className="adminTitleRow"><div><h3>{preview.fileName}</h3><p>{preview.totalQuestions}개 후보 · 오류/경고 {preview.totalErrors}건</p></div><button className="primary" disabled={busy||preview.weeks.some(w=>w.errors.some(e=>!e.includes("권장")))} onClick={()=>void commitImport()}>미리보기대로 등록</button></div>{preview.replacementDiff&&<div className="diffBox"><strong>교체 비교</strong><span>기존 {preview.replacementDiff.oldCount}개 → 새 파일 {preview.replacementDiff.newCount}개</span><small>추가 {preview.replacementDiff.added.length}개 · 삭제/변경 {preview.replacementDiff.removed.length}개 (최대 10개 미리보기)</small></div>}{preview.weeks.map(w=><div className="importWeek" key={w.sheetName}><strong>{w.sheetName} · {w.title}</strong><span>{w.questions.length}개 후보</span>{w.errors.map((e,i)=><small key={i}>{e}</small>)}</div>)}</section>}</>}
 {tab==="people"&&<><div className="adminTitleRow"><div><p className="eyebrow">DIRECTORY</p><h1>참가자 · 셀</h1></div><div><button className="ghost" onClick={()=>void addGroup()}>셀 추가</button> <button className="primary" onClick={()=>void addPerson()}>참가자 추가</button></div></div><div className="bulkBar"><strong>{selectedPeople.length}명 선택</strong><select value={moveGroup} onChange={e=>setMoveGroup(e.target.value)}>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><input type="date" value={moveDate} onChange={e=>setMoveDate(e.target.value)}/><button className="primary" disabled={!selectedPeople.length||busy} onClick={()=>void movePeople()}>선택 인원 셀 이동</button></div><div className="twoCols"><section className="adminPanel"><h3>참가자 {people.length}명</h3>{people.map(p=><label className="adminRow selectable" key={p.id}><span><input type="checkbox" checked={selectedPeople.includes(p.id)} onChange={e=>setSelectedPeople(v=>e.target.checked?[...v,p.id]:v.filter(x=>x!==p.id))}/> {p.display_name}</span><span><small>{p.group_name??"셀 미배정"}</small><button type="button" className="ghost" onClick={e=>{e.preventDefault();void togglePerson(p);}}>{p.active?"비활성":"활성"}</button></span></label>)}</section><section className="adminPanel"><h3>셀 {groups.length}개</h3>{groups.map(g=><div className="adminRow" key={g.id}><span>{g.name}</span><span><small>{g.active?"운영 중":"비활성"}</small> <button className="ghost" onClick={()=>void toggleGroup(g)}>{g.active?"비활성":"활성"}</button></span></div>)}</section></div></>}
 {tab==="season"&&<><p className="eyebrow">SEASON</p><h1>운영 Season</h1><section className="adminPanel"><div className="formGrid"><label>Season 이름<input value={seasonName} onChange={e=>setSeasonName(e.target.value)} placeholder="2027 청년부 1학기"/></label><label>시작일<input type="date" value={seasonStart} onChange={e=>setSeasonStart(e.target.value)}/></label><label>종료일<input type="date" value={seasonEnd} onChange={e=>setSeasonEnd(e.target.value)}/></label></div><button className="primary" disabled={!seasonName||!seasonStart||!seasonEnd} onClick={()=>void createSeasonUi()}>새 Season 만들고 활성화</button></section><section className="adminPanel"><h3>Season 목록</h3>{seasons.map(s=><div className="adminRow" key={s.id}><span><strong>{s.name}</strong><small>{s.starts_on} ~ {s.ends_on}</small></span><span className="statusPill">{s.active?"ACTIVE":"ARCHIVE"}</span></div>)}</section></>}
 {tab==="monthly"&&<><p className="eyebrow">MONTHLY SETTLEMENT</p><h1>월간 기간 · 결산</h1><section className="adminPanel"><div className="formGrid"><label>Season<select value={periodSeason} onChange={e=>setPeriodSeason(e.target.value)}>{seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>기간 이름<input value={periodName} onChange={e=>setPeriodName(e.target.value)} placeholder="2026년 10월"/></label><label>시작일<input type="date" value={periodStart} onChange={e=>setPeriodStart(e.target.value)}/></label><label>마지막 일요일<input type="date" value={periodEnd} onChange={e=>setPeriodEnd(e.target.value)}/></label></div><button className="primary" disabled={!periodSeason||!periodName||!periodStart||!periodEnd} onClick={()=>void createPeriodUi()}>월간 기간 만들기</button></section><section className="adminPanel"><h3>월간 결산</h3>{periods.map(p=><div className="adminRow" key={p.id}><span><strong>{p.name}</strong><small>{p.starts_on} ~ {p.ends_on}</small></span><span>{p.closed?<span className="statusPill">FINAL</span>:<button className="ghost" onClick={()=>void settlePeriodUi(p.id)}>결산 확정</button>}</span></div>)}</section></>}
 {tab==="special"&&<><p className="eyebrow">SPECIAL QUIZ</p><h1>Special 운영</h1><section className="adminPanel"><div className="formGrid"><label>제목<input value={specialTitle} onChange={e=>setSpecialTitle(e.target.value)} placeholder="성탄절 특별 퀴즈"/></label><label>방식<select value={specialMode} onChange={e=>setSpecialMode(e.target.value)}><option value="NORMAL">일반형</option><option value="RANKING">Ranking형</option><option value="PASS">PASS형</option></select></label>{specialMode==="PASS"&&<><label>PASS 점수<input type="range" min="0" max="100" step="5" value={passScore} onChange={e=>setPassScore(Number(e.target.value))}/><strong>{passScore}점</strong></label><label><input type="checkbox" checked={issuePass} onChange={e=>setIssuePass(e.target.checked)}/> PASS 입장권 발급</label><label>PASS 메시지<input value={specialMessage} onChange={e=>setSpecialMessage(e.target.value)} placeholder="축하합니다!"/></label></>}<label>재도전<select value={retryMode} onChange={e=>setRetryMode(e.target.value)}><option value="UNTIL_PASS">통과할 때까지</option><option value="NONE">재도전 없음</option><option value="MAX_ATTEMPTS">횟수 제한</option></select></label>{retryMode==="MAX_ATTEMPTS"&&<label>최대 도전<input type="number" min={1} max={20} value={maxAttempts} onChange={e=>setMaxAttempts(Number(e.target.value))}/></label>}<label>정답 공개<select value={answerRevealMode} onChange={e=>setAnswerRevealMode(e.target.value)}><option value="IMMEDIATE">제출 즉시</option><option value="AFTER_PASS">PASS 후</option><option value="AFTER_END">퀴즈 종료 후</option><option value="AT_TIME">지정 시간</option></select></label>{answerRevealMode==="AT_TIME"&&<label>정답 공개 시간<input type="datetime-local" value={answerRevealAt} onChange={e=>setAnswerRevealAt(e.target.value)}/></label>}</div><button className="primary" disabled={!specialTitle} onClick={()=>void createSpecialUi()}>Special 초안 만들기</button></section><section className="adminPanel"><h3>Special 목록</h3>{specials.map(s=><div className="adminRow" key={s.id}><span><strong>{s.title}</strong><small>{s.special?.special_mode??"NORMAL"} · PASS {s.special?.pass_score??"-"}</small></span><span className="statusPill">{s.status}</span></div>)}</section></>}
 {tab==="stats"&&<><p className="eyebrow">ADMIN ANALYTICS</p><h1>이번 주 통계</h1><div className="adminStats"><article><span>참여 제출</span><strong>{adminStats?.participation??0}</strong></article><article><span>평균 점수</span><strong>{adminStats?.average??"–"}점</strong></article><article><span>기준 퀴즈</span><strong>{adminStats?.quiz?.status??"–"}</strong></article></div><section className="adminPanel"><h3>문제별 정답률</h3>{(adminStats?.questions??[]).map((q:any,i:number)=><div className="adminRow" key={q.id}><span><strong>{i+1}. {q.prompt}</strong><small>{q.correct}/{q.total}명 정답</small></span><strong>{q.rate==null?"–":`${q.rate}%`}</strong></div>)}</section></>}{tab==="permissions"&&<><p className="eyebrow">ROLES & ACCESS</p><h1>Leader · Admin 권한</h1><section className="adminPanel"><p>권한을 부여하면 24시간 유효한 1회용 설정코드를 발급합니다. 대상자는 첫 운영자 진입 때 본인의 4자리 PIN을 직접 만듭니다.</p><div className="formGrid"><label>사람<select value={rolePerson} onChange={e=>setRolePerson(e.target.value)}>{people.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></label><label>권한<select value={role} onChange={e=>setRole(e.target.value as any)}><option value="LEADER">Leader</option><option value="ADMIN">Admin</option></select></label>{role==="LEADER"&&<label>담당 셀<select value={roleGroup} onChange={e=>setRoleGroup(e.target.value)}>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>}<label>적용일<input type="date" value={roleDate} onChange={e=>setRoleDate(e.target.value)}/></label></div><button className="primary" disabled={busy||!rolePerson} onClick={()=>void grantRole()}>권한 부여 + 설정코드 발급</button></section><section className="adminPanel"><h3>현재 운영자 권한</h3>{operators.map(o=><div className="adminRow" key={o.id}><span><strong>{o.name}</strong><small>{o.roles.map(r=>r.role+(r.target_group_id?" · 셀 지정":"")).join(" / ")}</small></span><span>{o.roles.map((r,i)=><button key={i} className="ghost" disabled={busy} onClick={()=>void revokeRole(o.id,r.role)}> {r.role} 해제 </button>)}</span></div>)}</section><section className="adminPanel pinChange"><h3>내 운영자 PIN 변경</h3><div className="formGrid"><label>현재 PIN<input inputMode="numeric" maxLength={4} value={currentPinChange} onChange={e=>setCurrentPinChange(e.target.value.replace(/\D/g,"").slice(0,4))}/></label><label>새 PIN<input inputMode="numeric" maxLength={4} value={newPinChange} onChange={e=>setNewPinChange(e.target.value.replace(/\D/g,"").slice(0,4))}/></label></div><button className="ghost" disabled={busy||currentPinChange.length!==4||newPinChange.length!==4} onClick={()=>void changePin()}>4자리 PIN 변경</button></section></>}
 </section></main>;
}
