const GROUPS=[{id:'g1',name:'이유신님 셀',members:[{id:'p1',name:'김민수',leader:true},{id:'p2',name:'박지훈'},{id:'p3',name:'이서연'},{id:'p4',name:'이정민'},{id:'p5',name:'정다은'}]},{id:'g2',name:'김민수님 셀',members:[{id:'p6',name:'최유진',leader:true},{id:'p7',name:'한지수'},{id:'p8',name:'윤하늘'}]},{id:'g3',name:'박지현님 셀',members:[{id:'p9',name:'박지현',leader:true},{id:'p10',name:'조은별'}]}];
const QUESTIONS=[
{id:'q1',type:'MCQ',text:'예수님께서 제자들에게 “너희는 세상의 무엇”이라고 말씀하셨나요?',source:'마태복음 5:14',choices:['소금','빛','양','포도나무'],answer:1,explanation:'예수님은 제자들을 “세상의 빛”이라고 부르셨습니다. 빛은 감추기보다 사람들 앞에서 하나님을 드러내는 삶을 가리킵니다.'},
{id:'q2',type:'OX',text:'예수님은 원수를 사랑하고 박해하는 사람을 위해 기도하라고 말씀하셨다.',source:'마태복음 5:44',choices:['O','X'],answer:0,explanation:'마태복음 5장 44절에서 예수님은 원수를 사랑하고 박해하는 자를 위하여 기도하라고 가르치십니다.'},
{id:'q3',type:'MCQ',text:'예수님이 기도를 가르치시며 “오늘 우리에게” 달라고 하신 것은 무엇인가요?',source:'마태복음 6:11',choices:['재물','지혜','일용할 양식','표적'],answer:2,explanation:'주기도문에는 “오늘 우리에게 일용할 양식을 주시옵고”라고 기록되어 있습니다.'},
{id:'q4',type:'OX',text:'예수님은 보물을 땅에만 쌓아 두라고 말씀하셨다.',source:'마태복음 6:19-20',choices:['O','X'],answer:1,explanation:'예수님은 땅이 아니라 하늘에 보물을 쌓으라고 말씀하셨습니다.'},
{id:'q5',type:'MCQ',text:'“먼저 그의 나라와 그의 의를 구하라”는 말씀은 어느 장에 나오나요?',source:'마태복음 6:33',choices:['마태복음 4장','마태복음 5장','마태복음 6장','마태복음 7장'],answer:2,explanation:'마태복음 6장 33절의 말씀입니다. 필요에 대한 염려보다 하나님의 나라와 의를 우선하라는 가르침입니다.'},
{id:'q6',type:'MCQ',text:'예수님은 다른 사람을 판단하기 전에 먼저 무엇을 보라고 하셨나요?',source:'마태복음 7:3-5',choices:['그의 열매','자기 눈 속의 들보','율법책','성전'],answer:1,explanation:'형제의 눈 속 티를 말하기 전에 자기 눈 속 들보를 먼저 보라고 하셨습니다.'},
{id:'q7',type:'OX',text:'예수님은 “구하라, 찾으라, 두드리라”고 말씀하셨다.',source:'마태복음 7:7',choices:['O','X'],answer:0,explanation:'마태복음 7장 7절에 “구하라… 찾으라… 두드리라”는 권면이 이어집니다.'},
{id:'q8',type:'MCQ',text:'예수님이 말씀하신 황금률에 가장 가까운 것은 무엇인가요?',source:'마태복음 7:12',choices:['받은 만큼만 돌려준다','남이 해주길 바라는 대로 남에게 한다','악한 사람은 피한다','모든 판단을 멈춘다'],answer:1,explanation:'“무엇이든지 남에게 대접을 받고자 하는 대로 너희도 남을 대접하라”는 말씀입니다.'},
{id:'q9',type:'OX',text:'좁은 문과 좁은 길은 생명으로 인도한다고 예수님이 말씀하셨다.',source:'마태복음 7:13-14',choices:['O','X'],answer:0,explanation:'예수님은 생명으로 인도하는 문은 좁고 길이 협착하다고 말씀하셨습니다.'},
{id:'q10',type:'MCQ',text:'산상수훈의 마지막 비유에서 말씀을 듣고 행하는 사람은 어디에 집을 지은 사람과 같나요?',source:'마태복음 7:24',choices:['모래 위','들판','반석 위','산꼭대기'],answer:2,explanation:'말씀을 듣고 행하는 사람은 반석 위에 집을 지은 지혜로운 사람과 같다고 하셨습니다.'}
];
const state={screen:'select',groupId:'g1',person:null,questionIndex:0,answers:Array(QUESTIONS.length).fill(null),result:null,modal:null};
const LS_KEY='weekly-cell-quiz-v01';
function save(){localStorage.setItem(LS_KEY,JSON.stringify({person:state.person,groupId:state.groupId,answers:state.answers,questionIndex:state.questionIndex,result:state.result}))}
function restore(){try{const x=JSON.parse(localStorage.getItem(LS_KEY));if(!x)return;Object.assign(state,x);if(x.person)state.screen='home'}catch(e){}}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function group(){return GROUPS.find(g=>g.id===state.groupId)||GROUPS[0]}
function header(){return `<div class="brand"><div><div class="brand-mark">주간 셀 퀴즈</div><small>GOD'S WORD, OUR DAILY LIFE</small></div><span class="pill">v0.1</span></div>`}
function render(){const app=document.querySelector('#app');app.innerHTML=({select:renderSelect,home:renderHome,intro:renderIntro,quiz:renderQuiz,result:renderResult,review:renderReview}[state.screen]||renderSelect)();bind();if(state.modal)app.insertAdjacentHTML('beforeend',renderModal())}
function renderSelect(){const g=group();return `${header()}<section class="hero"><h1>내 이름을<br>선택해주세요</h1><p>참여할 셀을 먼저 선택한 뒤, 이름을 선택해주세요.</p><div class="verse">“주의 말씀은 내 발에 등이요…”</div></section><section class="section"><div class="section-title"><h2>셀 선택</h2><span>${GROUPS.length}개 셀</span></div><div class="cell-tabs">${GROUPS.map(x=>`<button class="tab ${x.id===state.groupId?'active':''}" data-group="${x.id}">${esc(x.name)}</button>`).join('')}</div></section><section class="section"><div class="section-title"><h2>${esc(g.name)}</h2><span>리더 우선 · 가나다순</span></div><div class="people">${g.members.map(m=>`<button class="person ${m.leader?'leader':''}" data-person="${m.id}"><span>${esc(m.name)} <span class="meta">${m.leader?'셀 리더':''}</span></span><span>›</span></button>`).join('')}</div></section>`}
function renderHome(){return `${header()}<div class="welcome">${esc(state.person.name)}님,<br>반가워요.</div><div class="subtle">${esc(group().name)}</div><section class="section card weekly-card"><div class="weekly-art"><small>지난주 말씀 돌아보기</small><h3>10월 둘째 주 주간 셀 퀴즈</h3><small>마태복음 5:1–7:29 · 10문제</small></div><div class="weekly-body"><button class="btn btn-primary full" data-nav="intro">${state.result?'결과 보기':'퀴즈 시작하기'} →</button></div></section><section class="section"><div class="section-title"><h2>이번 달</h2><span>월간 기록이 메인</span></div><div class="card stats"><div class="stat"><strong>${state.result?state.result.score:0}점</strong><span>이번 달 누적</span></div><div class="stat"><strong>${state.result?'1/1':'0/1'}회</strong><span>참여</span></div></div></section>${state.result?`<section class="section"><button class="btn btn-secondary full" data-nav="review">정답과 말씀 다시 보기</button></section>`:''}`}
function renderIntro(){return `<div class="topbar"><button class="back" data-nav="home">‹</button><strong>주간 셀 퀴즈</strong><span></span></div><section class="question-scene" style="min-height:520px;display:flex;flex-direction:column;justify-content:space-between"><div><div class="eyebrow">지난주 말씀 돌아보기</div><h1 class="question" style="font-size:30px">10월 둘째 주<br>주간 셀 퀴즈</h1><p class="source">생명의삶 10월 1일–7일<br>마태복음 5:1–7:29</p></div><div class="card" style="background:rgba(255,252,244,.74)"><p><strong>10문제 · 100점 만점</strong></p><p class="subtle">제출 후 바로 정답과 설명을 볼 수 있어요.<br>공식 기록은 첫 제출만 저장됩니다.</p></div><button class="btn btn-primary full" data-start>시작하기 →</button></section>`}
function renderQuiz(){const q=QUESTIONS[state.questionIndex],answered=state.answers.filter(v=>v!==null).length;return `<div class="topbar"><button class="back" data-nav="home">‹</button><strong>주간 셀 퀴즈</strong><span>${state.questionIndex+1}/${QUESTIONS.length}</span></div><div class="progress"><span style="width:${(state.questionIndex+1)/QUESTIONS.length*100}%"></span></div><div class="navigator">${QUESTIONS.map((_,i)=>`<button class="qdot ${state.answers[i]!==null?'answered':''} ${i===state.questionIndex?'current':''}" data-q="${i}">${i+1}</button>`).join('')}</div><section class="question-scene"><div class="eyebrow">${q.type==='OX'?'O / X':'4지선다'} · Q${state.questionIndex+1}</div><div class="question">${esc(q.text)}</div><div class="source">${esc(q.source)}</div><div class="choices">${q.choices.map((c,i)=>`<button class="choice ${state.answers[state.questionIndex]===i?'selected':''}" data-choice="${i}"><span class="choice-index">${q.type==='OX'?c:i+1}</span><span>${esc(c)}</span></button>`).join('')}</div></section><div class="quiz-actions"><button class="btn btn-secondary" data-prev ${state.questionIndex===0?'disabled':''}>← 이전</button><button class="btn btn-primary" data-next>${state.questionIndex===QUESTIONS.length-1?'마지막':'다음 →'}</button></div><div class="submit-area"><button class="btn btn-ghost full" data-submit>제출하기 · ${answered}/${QUESTIONS.length} 답변</button></div>`}
function renderResult(){const r=state.result;return `${header()}<section class="result-hero"><div class="eyebrow" style="color:#edc27a">이번 주 기록</div><h1>수고했어요,<br>${esc(state.person.name)}님</h1><div class="score">${r.score}<span style="font-size:26px">점</span></div><div>${r.correct}/${r.total} 정답</div><p class="result-copy">이번 주도 말씀을 다시 돌아보는 시간을 내주셨네요.<br>오늘의 말씀이 한 주를 이어가길 바라요.</p></section><section class="section"><button class="btn btn-primary full" data-nav="review">정답과 설명 보기 →</button></section><section class="section card"><div class="eyebrow">한 주를 함께할 말씀</div><p style="font-family:Georgia,'Noto Serif KR',serif;line-height:1.7">“먼저 그의 나라와 그의 의를 구하라”</p><p class="source">마태복음 6:33</p></section><section class="section"><button class="btn btn-secondary full" data-nav="home">홈으로</button></section>`}
function renderReview(){return `<div class="topbar"><button class="back" data-nav="result">‹</button><strong>정답과 말씀 다시 보기</strong><span>${state.result.score}점</span></div><div class="review">${QUESTIONS.map((q,idx)=>{const a=state.answers[idx],good=a===q.answer;return `<article class="review-item"><div class="eyebrow">Q${idx+1} · ${esc(q.source)}</div><div class="review-q">${esc(q.text)}</div><div class="answer-line ${good?'good':'bad'}">${good?'✓ 내 답 · 정답':'✕ 내 답'}: ${a===null?'미답변':esc(q.choices[a])}</div>${good?'':`<div class="answer-line good">✓ 정답: ${esc(q.choices[q.answer])}</div>`}<div class="explain"><strong>말씀 다시 보기</strong><br>${esc(q.explanation)}</div></article>`}).join('')}</div><div class="bottom-space"></div><button class="btn btn-primary full" data-nav="home">홈으로</button>`}
function renderModal(){const m=state.modal;if(m.type==='person')return `<div class="modal-wrap"><div class="modal"><h3>${esc(m.person.name)}님 맞으신가요?</h3><p class="subtle">${esc(group().name)} · 이 이름으로 이번 주 기록이 저장됩니다.</p><div class="btn-row"><button class="btn btn-secondary" data-modal-close>아니에요</button><button class="btn btn-primary" data-person-confirm>맞아요</button></div></div></div>`;if(m.type==='submit')return `<div class="modal-wrap"><div class="modal"><h3>${m.missing.length?'아직 답하지 않은 문제가 있어요':'이대로 제출할까요?'}</h3><p class="subtle">${esc(state.person.name)}님의 이번 주 공식 기록으로 저장됩니다.</p>${m.missing.length?`<div class="missing">${m.missing.map(i=>`<span>${i+1}번</span>`).join('')}</div>`:''}<div class="btn-row"><button class="btn btn-secondary" data-modal-close>${m.missing.length?'문제로 돌아가기':'돌아가기'}</button><button class="btn btn-primary" data-confirm-submit>${m.missing.length?'그래도 제출':'제출하기'}</button></div></div></div>`;return ''}
function bind(){document.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{state.groupId=b.dataset.group;render()});document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{const p=group().members.find(x=>x.id===b.dataset.person);state.modal={type:'person',person:p};render()});document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{const n=b.dataset.nav;if(n==='intro'&&state.result)state.screen='result';else state.screen=n;render()});const start=document.querySelector('[data-start]');if(start)start.onclick=()=>{state.screen='quiz';state.questionIndex=0;save();render()};document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{state.questionIndex=Number(b.dataset.q);save();render()});document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{state.answers[state.questionIndex]=Number(b.dataset.choice);save();render()});const prev=document.querySelector('[data-prev]');if(prev)prev.onclick=()=>{if(state.questionIndex>0){state.questionIndex--;save();render()}};const next=document.querySelector('[data-next]');if(next)next.onclick=()=>{if(state.questionIndex<QUESTIONS.length-1){state.questionIndex++;save();render()}else openSubmit()};const submit=document.querySelector('[data-submit]');if(submit)submit.onclick=openSubmit;document.querySelectorAll('[data-modal-close]').forEach(b=>b.onclick=()=>{state.modal=null;render()});const pc=document.querySelector('[data-person-confirm]');if(pc)pc.onclick=()=>{state.person=state.modal.person;state.modal=null;state.screen='home';save();render()};const cs=document.querySelector('[data-confirm-submit]');if(cs)cs.onclick=doSubmit}
function openSubmit(){state.modal={type:'submit',missing:state.answers.map((a,i)=>a===null?i:null).filter(i=>i!==null)};render()}
function doSubmit(){const correct=QUESTIONS.reduce((n,q,i)=>n+(state.answers[i]===q.answer?1:0),0);state.result={correct,total:QUESTIONS.length,score:Math.round(correct/QUESTIONS.length*100),submittedAt:new Date().toISOString()};state.modal=null;state.screen='result';save();render()}
restore();render();
