import fs from 'node:fs';
function patch(path, reps){let s=fs.readFileSync(path,'utf8');for(const [a,b] of reps){if(!s.includes(a))throw new Error(`patch target missing in ${path}: ${a.slice(0,80)}`);s=s.replace(a,b)}fs.writeFileSync(path,s)}

patch('package.json', [['"version": "1.4.3"','"version": "1.4.4"']]);

patch('src/server/excelImport.ts', [
['export type ImportWeek = { sheetName:string; quizType:"WEEKLY"|"SPECIAL"; title:string; lifeDateRange:string; bibleRange:string; openAt:string; closeAt:string; memo:string; questions:ImportQuestion[]; errors:string[] };','export type ImportWeek = { sheetName:string; quizType:"WEEKLY"|"SPECIAL"; title:string; lifeDateRange:string; bibleRange:string; openAt:string; closeAt:string; memo:string; questions:ImportQuestion[]; errors:string[]; quizMonthKey:string|null; quizWeekIndex:number|null; quizLabel:string|null };'],
['function difficultyOf(v:unknown){const s=str(v).toUpperCase();return (["EASY","MEDIUM","HARD"].includes(s)?s:"MEDIUM") as "EASY"|"MEDIUM"|"HARD";}\n','function difficultyOf(v:unknown){const s=str(v).toUpperCase();return (["EASY","MEDIUM","HARD"].includes(s)?s:"MEDIUM") as "EASY"|"MEDIUM"|"HARD";}\n\nfunction deriveQuizCycle(lifeDateRange:string){\n  const m=lifeDateRange.match(/(20\\d{2})-(\\d{2})-(\\d{2})\\s*~\\s*(20\\d{2})-(\\d{2})-(\\d{2})/);\n  if(!m)return null;\n  const endUtc=new Date(Date.UTC(Number(m[4]),Number(m[5])-1,Number(m[6]),12,0,0));\n  const day=endUtc.getUTCDay(); const daysToMonday=((8-day)%7)||7;\n  const start=new Date(endUtc); start.setUTCDate(endUtc.getUTCDate()+daysToMonday);\n  const close=new Date(start); close.setUTCDate(start.getUTCDate()+5);\n  const yyyy=start.getUTCFullYear(), mm=start.getUTCMonth()+1, dd=start.getUTCDate();\n  const cy=close.getUTCFullYear(), cm=close.getUTCMonth()+1, cd=close.getUTCDate();\n  const weekIndex=Math.max(1,Math.ceil(cd/7));\n  const ord=["첫째","둘째","셋째","넷째","다섯째","여섯째"][weekIndex-1]??`${weekIndex}주차`;\n  const pad=(n:number)=>String(n).padStart(2,"0");\n  return {openAt:`${yyyy}-${pad(mm)}-${pad(dd)}T00:00:00+09:00`,closeAt:`${cy}-${pad(cm)}-${pad(cd)}T23:59:00+09:00`,monthKey:`${cy}-${pad(cm)}`,weekIndex,title:`${cm}월 ${ord} 주간 셀 퀴즈`,label:`${cm}월 ${weekIndex}주차 · ${mm}/${dd}–${cm}/${cd}`};\n}\n'],
['    const quizType: "WEEKLY"|"SPECIAL" = sheetName==="스페셜"?"SPECIAL":"WEEKLY";\n    const week:ImportWeek={sheetName,quizType,title:meta("퀴즈제목")||(quizType==="SPECIAL"?"스페셜 퀴즈":`${sheetName} 주간 셀 퀴즈`),lifeDateRange:meta("생명의삶 기간"),bibleRange:meta("성경범위"),openAt:meta("공개일시"),closeAt:meta("마감일시"),memo:meta("출제메모"),questions:[],errors:[]};','    const quizType: "WEEKLY"|"SPECIAL" = sheetName==="스페셜"?"SPECIAL":"WEEKLY";\n    const lifeDateRange=meta("생명의삶 기간"); const derived=quizType==="WEEKLY"?deriveQuizCycle(lifeDateRange):null;\n    const manualOpen=meta("공개일시"), manualClose=meta("마감일시");\n    const week:ImportWeek={sheetName,quizType,title:quizType==="SPECIAL"?(meta("퀴즈제목")||"스페셜 퀴즈"):(derived?.title||meta("퀴즈제목")||`${sheetName} 주간 셀 퀴즈`),lifeDateRange,bibleRange:meta("성경범위"),openAt:manualOpen||derived?.openAt||"",closeAt:manualClose||derived?.closeAt||"",memo:meta("출제메모"),questions:[],errors:[],quizMonthKey:derived?.monthKey??null,quizWeekIndex:derived?.weekIndex??null,quizLabel:derived?.label??null};']
]);

patch('src/app/api/admin/import/commit/route.ts', [
['type Week={sheetName:string;quizType?:"WEEKLY"|"SPECIAL";title:string;lifeDateRange:string;bibleRange:string;openAt:string;closeAt:string;questions:Q[];errors:string[]};','type Week={sheetName:string;quizType?:"WEEKLY"|"SPECIAL";title:string;lifeDateRange:string;bibleRange:string;openAt:string;closeAt:string;questions:Q[];errors:string[];quizMonthKey?:string|null;quizWeekIndex?:number|null;quizLabel?:string|null};'],
['type ExistingQuiz={id:string;status:string;quiz_type:"WEEKLY"|"SPECIAL";content_week_index:number|null;title:string;life_date_range:string|null};','type ExistingQuiz={id:string;status:string;quiz_type:"WEEKLY"|"SPECIAL";content_month_key:string|null;content_week_index:number|null;title:string;life_date_range:string|null;open_at?:string|null;close_at?:string|null};'],
['function weekIndex(sheetName:string){return Number(sheetName.match(/^(\\d+)주차$/)?.[1]||0)||null;}\nfunction sameProtectedWeek(w:Week,q:ExistingQuiz){\n const wi=weekIndex(w.sheetName);\n if(wi&&q.content_week_index===wi)return true;\n if(w.title.trim()===q.title.trim())return true;\n // 말씀 기간만 같은 것은 같은 Quiz 주차로 보지 않는다. 과거 주차 보정 시 같은 본문이 다음 주 Quiz로 이월될 수 있다.\n return false;\n}','function sameProtectedWeek(w:Week,q:ExistingQuiz){\n const month=w.quizMonthKey??null, wi=w.quizWeekIndex??null;\n if(month&&wi&&q.content_month_key===month&&q.content_week_index===wi)return true;\n if(w.openAt&&q.open_at&&new Date(w.openAt).getTime()===new Date(q.open_at).getTime())return true;\n return w.title.trim()===q.title.trim();\n}'],
['    const tagged=await supabaseRest<Array<{id:string}>>(`quizzes?quiz_type=eq.WEEKLY&content_month_key=eq.${inferredMonthKey}&select=id`);\n    tagged.forEach(x=>quizIds.add(x.id));','    const incomingMonthKeys=[...new Set(body.weeks.map(w=>w.quizMonthKey).filter(Boolean) as string[])];\n    for(const mk of incomingMonthKeys){const tagged=await supabaseRest<Array<{id:string}>>(`quizzes?quiz_type=eq.WEEKLY&content_month_key=eq.${mk}&select=id`);tagged.forEach(x=>quizIds.add(x.id));}'],
['select=id,status,quiz_type,content_week_index,title,life_date_range','select=id,status,quiz_type,content_month_key,content_week_index,title,life_date_range,open_at,close_at'],
['select=id,status,quiz_type,content_week_index,title,life_date_range','select=id,status,quiz_type,content_month_key,content_week_index,title,life_date_range,open_at,close_at'],
['    const wi=qt==="SPECIAL"?null:weekIndex(w.sheetName);\n    const qs=await supabaseRest<Array<{id:string}>>("quizzes?select=id",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({title:w.title,quiz_type:qt,status:"DRAFT",life_date_range:w.lifeDateRange||null,bible_range:w.bibleRange||null,open_at:w.openAt||null,close_at:w.closeAt||null,selection_mode:"FIXED",content_month_key:inferredMonthKey,content_week_index:wi,import_id:importId})});','    const wi=qt==="SPECIAL"?null:(w.quizWeekIndex??null); const quizMonthKey=qt==="SPECIAL"?null:(w.quizMonthKey??inferredMonthKey);\n    const qs=await supabaseRest<Array<{id:string}>>("quizzes?select=id",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({title:w.title,quiz_type:qt,status:"DRAFT",life_date_range:w.lifeDateRange||null,bible_range:w.bibleRange||null,open_at:w.openAt||null,close_at:w.closeAt||null,selection_mode:"FIXED",content_month_key:quizMonthKey,content_week_index:wi,import_id:importId})});']
]);

patch('src/app/operator/page.tsx', [
['weeks:Array<{sheetName:string;title:string;lifeDateRange:string;bibleRange:string;openAt:string;closeAt:string;memo:string;questions:any[];errors:string[]}>','weeks:Array<{sheetName:string;title:string;lifeDateRange:string;bibleRange:string;openAt:string;closeAt:string;memo:string;questions:any[];errors:string[];quizMonthKey?:string|null;quizWeekIndex?:number|null;quizLabel?:string|null}>'],
['Excel의 1주차~5주차는 <strong>말씀 기간</strong> 기준입니다.','Excel의 1주차~6주차는 <strong>말씀 기간</strong> 기준입니다.'],
['{preview.weeks.map(w=><div className="importWeek" key={w.sheetName}><strong>{w.sheetName} · {w.title}</strong><span>{w.questions.length}개 후보 · 힌트 {w.questions.filter((q:any)=>Boolean(q.hint)).length}개</span>{w.errors.map((e,i)=><small key={i}>{e}</small>)}</div>)}','{preview.weeks.map(w=><div className="importWeek" key={w.sheetName}><strong>{w.sheetName} → {w.quizLabel||w.title}</strong><span>{w.questions.length}개 후보 · 힌트 {w.questions.filter((q:any)=>Boolean(q.hint)).length}개</span>{w.lifeDateRange&&<small>말씀 {w.lifeDateRange}</small>}{w.errors.map((e,i)=><small key={i}>{e}</small>)}</div>)}']
]);

patch('src/app/globals.css', [
['.adminNav nav{display:grid;gap:5px;margin-top:32px}', '.adminNav nav{display:grid;gap:5px;margin-top:44px}'],
['.introGuide{margin:16px 0 10px;padding:18px}', '.introGuide{margin:10px 0 6px;padding:14px 16px}'],
['.introScene .meditationCard{margin-top:4px}', '.introScene .meditationCard{margin-top:0}'],
['.introScene>.btnPrimary{margin-top:14px}', '.introScene>.btnPrimary{margin-top:10px}']
]);